/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    CiRedo: typeof import('~icons/ci/redo')['default']
    IcOutlineLockOpen: typeof import('~icons/ic/outline-lock-open')['default']
    IcOutlineLockPerson: typeof import('~icons/ic/outline-lock-person')['default']
    IcRoundClose: typeof import('~icons/ic/round-close')['default']
    IcRoundNavigateNext: typeof import('~icons/ic/round-navigate-next')['default']
    MaterialSymbolsLockOutline: typeof import('~icons/material-symbols/lock-outline')['default']
    MdiLockOpenVariantOutline: typeof import('~icons/mdi/lock-open-variant-outline')['default']
    StepProgress: typeof import('./src/components/StepProgress.vue')['default']
    Task: typeof import('./src/components/Task.vue')['default']
  }
}
