/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    IcOutlineLockPerson: typeof import('~icons/ic/outline-lock-person')['default']
    IcRoundClose: typeof import('~icons/ic/round-close')['default']
    Task: typeof import('./src/components/Task.vue')['default']
    Versions: typeof import('./src/components/Versions.vue')['default']
  }
}
